name: AeroBeach Frontend
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: docker
    container:
      image: node:24-alpine
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Run Tests
        working-directory: frontend
        run: npm run test

      - uses: actions/upload-artifact@v3
        name: Upload Artifact
        with:
          name: dist
          path: frontend/dist

  build-docker:
    name: Build Docker image
    needs: [build-and-test]
    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/master'
    runs-on: docker
    container:
      image: node:20-alpine
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        name: Download Artifact
        with:
          name: dist
          path: frontend/dist

      - uses: https://git.lhprovedor.com.br/leandro/devops/.forgejo/actions/build-docker@main
        env:
          IMAGE_NAME: ${{ github.ref == 'refs/heads/development' && 'aero-beach-frontend-dev' || 'aero-beach-frontend' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          context: frontend
