services:
  frontend:
    image: leandrocostaaca/aero-beach-frontend
    restart: unless-stopped
    ports:
      - 80:80
  backend:
    image: leandrocostaaca/aero-beach-backend
    restart: unless-stopped
    environment:
      JWT_SECRET: REDACTED
    ports:
      - 3000:3000
    volumes:
      - ./aerobeach.db:/app/aerobeach.db

  frontend-dev:
    image: leandrocostaaca/aero-beach-frontend-dev
    restart: unless-stopped
    ports:
      - 81:80
  backend-dev:
    image: leandrocostaaca/aero-beach-backend-dev
    restart: unless-stopped
    environment:
      JWT_SECRET: REDACTED
    ports:
      - 3001:3000
    volumes:
      - ./aerobeach-dev.db:/app/aerobeach.db

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --schedule "0 */5 * * * *" --cleanup --rolling-restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
      - /etc/hostname:/etc/hostname:ro
    environment:
      TZ: America/Fortaleza
      DOCKER_API_VERSION: 1.44
